name: check for new Sentinel planned acquisitions

#when it should run
on:
  schedule:
    - cron: "0 5 * * *" #run everyday at utc 5

#create jobs    
jobs:
  sent: 
    runs-on: windows-latest
    
    steps: 

    # load repo
    - uses: actions/checkout@master

    # setup r
    - uses: r-lib/actions/setup-r@master

    # install packages
    - name: Install packages
      run: |
        install.packages('rvest')
        install.packages('stringr')
        install.packages('sf')
        install.packages('rgdal')
        install.packages('xml2')
        install.packages('tidyverse')
        install.packages('lubridate')
      shell: Rscript {0}

    # run script
    - name: Check for new acquisition .kml files, download and collate if present
      run: |
        source('check_source_save.R')
      shell: Rscript {0}

    #commit files to GH  
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add EPSCoRBlooms_Sentinel_future*
        git add archive/*
        git commit -am "gh action sentinel acquisition download $(date)"
        git push origin main
